# Based on https://docs.codecov.com/docs/codecov-yaml#default-yaml
codecov:
  require_ci_to_pass: yes

comment: false

coverage:
  precision: 2
  round: down
  range: "50...95"
  status:
    patch: off
    project:
      default:
        target: 80%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
