import * as VRM0Type from "@pixiv/types-vrm-0.0";
import * as VRM1Type from "@pixiv/types-vrmc-vrm-1.0";

export enum PropertyType {
  HUMANOID = "VRMC_vrm.humanoid",
  HUMANOID_HUMAN_BONE = "VRMC_vrm.humanoid.humanBone",
}

export type LicenseName =
  | "Redistribution_Prohibited"
  | "CC0"
  | "CC_BY"
  | "CC_BY_NC"
  | "CC_BY_SA"
  | "CC_BY_NC_SA"
  | "CC_BY_ND"
  | "CC_BY_NC_ND"
  | "Other";

export const LICENSE_TO_URL_MAP = new Map<LicenseName, string>([
  ["CC0", "https://creativecommons.org/public-domain/cc0/"],
  ["CC_BY", "https://creativecommons.org/licenses/by/2.0/deed"],
  ["CC_BY_NC", "https://creativecommons.org/licenses/by-nc/2.0/deed"],
  ["CC_BY_SA", "https://creativecommons.org/licenses/by-sa/2.0/deed"],
  ["CC_BY_NC_SA", "https://creativecommons.org/licenses/by-nc-sa/2.0/deed"],
  ["CC_BY_ND", "https://creativecommons.org/licenses/by-nd/2.0/deed"],
  ["CC_BY_NC_ND", "https://creativecommons.org/licenses/by-nc-nd/2.0/deed"],
]);

export const URL_TO_LICENSE_MAP = new Map<string, LicenseName>([
  ["https://creativecommons.org/public-domain/cc0/", "CC0"],
  ["https://creativecommons.org/licenses/by/2.0/deed", "CC_BY"],
  ["https://creativecommons.org/licenses/by-nc/2.0/deed", "CC_BY_NC"],
  ["https://creativecommons.org/licenses/by-sa/2.0/deed", "CC_BY_SA"],
  ["https://creativecommons.org/licenses/by-nc-sa/2.0/deed", "CC_BY_NC_SA"],
  ["https://creativecommons.org/licenses/by-nd/2.0/deed", "CC_BY_ND"],
  ["https://creativecommons.org/licenses/by-nc-nd/2.0/deed", "CC_BY_NC_ND"],
]);

export const VRM0_BONE_ORDER: VRM0Type.HumanoidBoneName[] = [
  "hips",
  "spine",
  "chest",
  "upperChest",
  "neck",
  "head",
  "leftEye",
  "rightEye",
  "jaw",
  "leftUpperLeg",
  "leftLowerLeg",
  "leftFoot",
  "leftToes",
  "rightUpperLeg",
  "rightLowerLeg",
  "rightFoot",
  "rightToes",
  "leftShoulder",
  "leftUpperArm",
  "leftLowerArm",
  "leftHand",
  "rightShoulder",
  "rightUpperArm",
  "rightLowerArm",
  "rightHand",
  "leftThumbIntermediate",
  "leftThumbProximal",
  "leftThumbDistal",
  "leftIndexProximal",
  "leftIndexIntermediate",
  "leftIndexDistal",
  "leftMiddleProximal",
  "leftMiddleIntermediate",
  "leftMiddleDistal",
  "leftRingProximal",
  "leftRingIntermediate",
  "leftRingDistal",
  "leftLittleProximal",
  "leftLittleIntermediate",
  "leftLittleDistal",
  "rightThumbIntermediate",
  "rightThumbProximal",
  "rightThumbDistal",
  "rightIndexProximal",
  "rightIndexIntermediate",
  "rightIndexDistal",
  "rightMiddleProximal",
  "rightMiddleIntermediate",
  "rightMiddleDistal",
  "rightRingProximal",
  "rightRingIntermediate",
  "rightRingDistal",
  "rightLittleProximal",
  "rightLittleIntermediate",
  "rightLittleDistal",
];

export const VRM1_BONE_ORDER: VRM1Type.HumanoidHumanBoneName[] = [
  "hips",
  "spine",
  "chest",
  "upperChest",
  "neck",
  "head",
  "leftEye",
  "rightEye",
  "jaw",
  "leftUpperLeg",
  "leftLowerLeg",
  "leftFoot",
  "leftToes",
  "rightUpperLeg",
  "rightLowerLeg",
  "rightFoot",
  "rightToes",
  "leftShoulder",
  "leftUpperArm",
  "leftLowerArm",
  "leftHand",
  "rightShoulder",
  "rightUpperArm",
  "rightLowerArm",
  "rightHand",
  "leftThumbProximal",
  "leftThumbMetacarpal",
  "leftThumbDistal",
  "leftIndexProximal",
  "leftIndexIntermediate",
  "leftIndexDistal",
  "leftMiddleProximal",
  "leftMiddleIntermediate",
  "leftMiddleDistal",
  "leftRingProximal",
  "leftRingIntermediate",
  "leftRingDistal",
  "leftLittleProximal",
  "leftLittleIntermediate",
  "leftLittleDistal",
  "rightThumbProximal",
  "rightThumbMetacarpal",
  "rightThumbDistal",
  "rightIndexProximal",
  "rightIndexIntermediate",
  "rightIndexDistal",
  "rightMiddleProximal",
  "rightMiddleIntermediate",
  "rightMiddleDistal",
  "rightRingProximal",
  "rightRingIntermediate",
  "rightRingDistal",
  "rightLittleProximal",
  "rightLittleIntermediate",
  "rightLittleDistal",
];

export const VRM1_BONE_TO_VRM0_BONE = new Map<
  VRM1Type.HumanoidHumanBoneName,
  VRM0Type.HumanoidBoneName
>([
  ["hips", "hips"],
  ["spine", "spine"],
  ["chest", "chest"],
  ["upperChest", "upperChest"],
  ["neck", "neck"],
  ["head", "head"],
  ["leftEye", "leftEye"],
  ["rightEye", "rightEye"],
  ["jaw", "jaw"],
  ["leftUpperLeg", "leftUpperLeg"],
  ["leftLowerLeg", "leftLowerLeg"],
  ["leftFoot", "leftFoot"],
  ["leftToes", "leftToes"],
  ["rightUpperLeg", "rightUpperLeg"],
  ["rightLowerLeg", "rightLowerLeg"],
  ["rightFoot", "rightFoot"],
  ["rightToes", "rightToes"],
  ["leftShoulder", "leftShoulder"],
  ["leftUpperArm", "leftUpperArm"],
  ["leftLowerArm", "leftLowerArm"],
  ["leftHand", "leftHand"],
  ["rightShoulder", "rightShoulder"],
  ["rightUpperArm", "rightUpperArm"],
  ["rightLowerArm", "rightLowerArm"],
  ["rightHand", "rightHand"],

  ["leftThumbProximal", "leftThumbProximal"],
  ["leftThumbMetacarpal", "leftThumbIntermediate"],
  ["leftThumbDistal", "leftThumbDistal"],
  ["leftIndexProximal", "leftIndexProximal"],
  ["leftIndexIntermediate", "leftIndexIntermediate"],
  ["leftIndexDistal", "leftIndexDistal"],
  ["leftMiddleProximal", "leftMiddleProximal"],
  ["leftMiddleIntermediate", "leftMiddleIntermediate"],
  ["leftMiddleDistal", "leftMiddleDistal"],
  ["leftRingProximal", "leftRingProximal"],
  ["leftRingIntermediate", "leftRingIntermediate"],
  ["leftRingDistal", "leftRingDistal"],
  ["leftLittleProximal", "leftLittleProximal"],
  ["leftLittleIntermediate", "leftLittleIntermediate"],
  ["leftLittleDistal", "leftLittleDistal"],

  ["rightThumbProximal", "rightThumbProximal"],
  ["rightThumbMetacarpal", "rightThumbIntermediate"],
  ["rightThumbDistal", "rightThumbDistal"],
  ["rightIndexProximal", "rightIndexProximal"],
  ["rightIndexIntermediate", "rightIndexIntermediate"],
  ["rightIndexDistal", "rightIndexDistal"],
  ["rightMiddleProximal", "rightMiddleProximal"],
  ["rightMiddleIntermediate", "rightMiddleIntermediate"],
  ["rightMiddleDistal", "rightMiddleDistal"],
  ["rightRingProximal", "rightRingProximal"],
  ["rightRingIntermediate", "rightRingIntermediate"],
  ["rightRingDistal", "rightRingDistal"],
  ["rightLittleProximal", "rightLittleProximal"],
  ["rightLittleIntermediate", "rightLittleIntermediate"],
  ["rightLittleDistal", "rightLittleDistal"],
]);

export const VRM0_BONE_TO_VRM1_BONE = new Map<
  VRM0Type.HumanoidBoneName,
  VRM1Type.HumanoidHumanBoneName
>([
  ["hips", "hips"],
  ["spine", "spine"],
  ["chest", "chest"],
  ["upperChest", "upperChest"],
  ["neck", "neck"],
  ["head", "head"],
  ["leftEye", "leftEye"],
  ["rightEye", "rightEye"],
  ["jaw", "jaw"],
  ["leftUpperLeg", "leftUpperLeg"],
  ["leftLowerLeg", "leftLowerLeg"],
  ["leftFoot", "leftFoot"],
  ["leftToes", "leftToes"],
  ["rightUpperLeg", "rightUpperLeg"],
  ["rightLowerLeg", "rightLowerLeg"],
  ["rightFoot", "rightFoot"],
  ["rightToes", "rightToes"],
  ["leftShoulder", "leftShoulder"],
  ["leftUpperArm", "leftUpperArm"],
  ["leftLowerArm", "leftLowerArm"],
  ["leftHand", "leftHand"],
  ["rightShoulder", "rightShoulder"],
  ["rightUpperArm", "rightUpperArm"],
  ["rightLowerArm", "rightLowerArm"],
  ["rightHand", "rightHand"],

  ["leftThumbProximal", "leftThumbProximal"],
  ["leftThumbIntermediate", "leftThumbMetacarpal"],
  ["leftThumbDistal", "leftThumbDistal"],
  ["leftIndexProximal", "leftIndexProximal"],
  ["leftIndexIntermediate", "leftIndexIntermediate"],
  ["leftIndexDistal", "leftIndexDistal"],
  ["leftMiddleProximal", "leftMiddleProximal"],
  ["leftMiddleIntermediate", "leftMiddleIntermediate"],
  ["leftMiddleDistal", "leftMiddleDistal"],
  ["leftRingProximal", "leftRingProximal"],
  ["leftRingIntermediate", "leftRingIntermediate"],
  ["leftRingDistal", "leftRingDistal"],
  ["leftLittleProximal", "leftLittleProximal"],
  ["leftLittleIntermediate", "leftLittleIntermediate"],
  ["leftLittleDistal", "leftLittleDistal"],

  ["rightThumbProximal", "rightThumbProximal"],
  ["rightThumbIntermediate", "rightThumbMetacarpal"],
  ["rightThumbDistal", "rightThumbDistal"],
  ["rightIndexProximal", "rightIndexProximal"],
  ["rightIndexIntermediate", "rightIndexIntermediate"],
  ["rightIndexDistal", "rightIndexDistal"],
  ["rightMiddleProximal", "rightMiddleProximal"],
  ["rightMiddleIntermediate", "rightMiddleIntermediate"],
  ["rightMiddleDistal", "rightMiddleDistal"],
  ["rightRingProximal", "rightRingProximal"],
  ["rightRingIntermediate", "rightRingIntermediate"],
  ["rightRingDistal", "rightRingDistal"],
  ["rightLittleProximal", "rightLittleProximal"],
  ["rightLittleIntermediate", "rightLittleIntermediate"],
  ["rightLittleDistal", "rightLittleDistal"],
]);
