name: coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      CI: true
    steps:
    # Setup.
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Cache.
    - id: yarn-cache-dir
      run: echo "{yarn_cache_dir}=$(yarn cache dir)" >> $GITHUB_ENV
    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ env.yarn_cache_dir }}
        key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ hashFiles('./yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-yarn-

    # Build.
    - run: yarn install
    - run: yarn dist

    # Coverage.
    - name: Run coverage
      # No worker threads on CI: https://github.com/avajs/ava/discussions/3158
      run: |
        yarn coverage --no-worker-threads
        yarn coverage:report
    - name: Report coverage
      uses: codecov/codecov-action@v3
      with:
        files: coverage/coverage.lcov
